### ISSUE TITLE
Add a scroll area to the Contents

### ISSUE THREAD

**Issue by adib-yg** [openmultiplayer/web#925]
I just added a div and styled it
```css
.scroll {
    height: 800px;
    width: 100%;
    max-width: 1000px;
    overflow: auto;
    overflow-x: hidden;
}
```

https://github.com/openmultiplayer/web/assets/92677767/bc03f0f6-2856-44b8-823e-8c9e594f63a8

It looks more organized.
But it's not responsive.
